const streamText = [
    " ",
    "...",
    "Hello! 👋",
    "I'm glad to see you here.",
    "I hope you're doing well.",
    "You must be here to learn more about me.",
    "Before we dive in ...",
    "Can we take a moment together?",
    "Just you and me.",
    "A simple moment of reflection.",
    "A silent meditation paired with a breathing exercise.",
    "Right now.",
    "I'm serious.",
    "I know it might feel a bit weird.",
    "But let's give it a try.",
    "For the sake of stillness.",
    "Everyone is busy.",
    "Everyone is stressed.",
    "Everyone is anxious.",
    "That we forget to be still.",
    " ",
    "Let's simply stay still and quiet.",
    "Only for a short moment.",
    "Ready?",
    "Here we go.",
    " ",
    "Inhale...",
    "1",
    "2",
    "3",
    "4",
    "5",
    "Exhale...",
    "1",
    "2",
    "3",
    "4",
    "5",
    "Inhale...",
    "1",
    "2",
    "3",
    "4",
    "5",
    "Exhale...",
    "1",
    "2",
    "3",
    "4",
    "5",
    "Inhale...",
    "1",
    "2",
    "3",
    "4",
    "5",
    "Exhale...",
    "1",
    "2",
    "3",
    "4",
    "5",
    "Let your mind be still.",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    "How do you feel?",
    "It's amazing how stillness",
    "can change our state of mind.",
    " ",
    "Now, I guess it's time to tell you a bit about myself.",
    " ",
    "I'm an artist,",
    "a creator,",
    "and a dreamer.",
    " ",
    "I've spent years creating art,",
    "building things,",
    "and bringing ideas to life.",
    " ",
    "My journey has taken me through",
    "many adventures in various fields.",
    "Each step teaching me something new.",
    " ",
    "But enough about me.",
    "Let's talk about you.",
    "What brings you here?",
    "What are your aspirations?",
    "Your dreams?",
    " ",
    "Take a moment to reflect.",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    "Just a bit longer.",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    "...",
    " ",
    "In my work, I strive for",
    "clarity, creativity, and compassion.",
    "I believe in the power of design",
    "to make the world a better place.",
    " ",
    "Through each project,",
    "I aim to bring a touch of joy,",
    "a hint of wisdom,",
    "and a spark of inspiration.",
    " ",
    "I know these are big ideals,",
    "but they guide me in everything I do.",
    " ",
    " ",
    "Thank you for joining me.",
    "For sharing this space and time.",
    " ",
    "If you'd like to see more of my work,",
    "feel free to explore my site.",
    "Or stay a while and listen.",
    "The choice is yours.",
    " ",
    "...",
    "I think our last meditation was a bit short.",
    " ",
    "Let's do another one.",
    " ",
    "Ready?",
    "Here we go.",
    " ",
    "Inhale...",
    "1",
    "2",
    "3",
    "4",
    "5",
    "Exhale...",
    "1",
    "2",
    "3",
    "4",
    "5",
    "Inhale...",
    "1",
    "2",
    "3",
    "4",
    "5",
    "Exhale...",
    "1",
    "2",
    "3",
    "4",
    "5",
    "Inhale...",
    "1",
    "2",
    "3",
    "4",
    "5",
    "Exhale...",
    "1",
    "2",
    "3",
    "4",
    "5",
    "Let your mind be still.",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    "Take a moment to reflect.",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    "Just a bit longer.",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    "...",
    " ",
    "Remember,",
    "You are capable,",
    "You are creative,",
    "And you are important.",
    " ",
    "Peace, love, and inspiration.",
    " ",
    "...",
    "Until next time,",
    "Take care.",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
  ];
  
  export default streamText;