const streamText = [
    " ",
    "...",
    "Hello there! 👋",
    "I hope you're doing well.",
    "I'm here to share something special with you.",
    "Before we dive in ...",
    "Can we take a moment together?",
    "Just you and me.",
    "A simple moment of awareness.",
    "Right now.",
    "I know it might feel a bit odd.",
    "But let's give it a try.",
    "For the sake of connection.",
    " ",
    "Let's begin with a deep breath.",
    "Ready?",
    "Here we go.",
    " ",
    "Inhale ...",
    "5",
    "4",
    "3",
    "2",
    "1",
    "Hold ...",
    "5",
    "4",
    "3",
    "2",
    "1",
    "Exhale ...",
    "5",
    "4",
    "3",
    "2",
    "1",
    " ",
    " ",
    "How do you feel?",
    "It's amazing how a single breath",
    "can change our state of mind.",
    " ",
    "Now, let me tell you a bit about myself.",
    "I'm a creator,",
    "an innovator,",
    "and a dreamer.",
    "I've spent years crafting designs,",
    "building solutions,",
    "and bringing ideas to life.",
    " ",
    "My journey has taken me through",
    "many adventures in the tech world.",
    "From startups to established firms.",
    "Each step teaching me something new.",
    " ",
    "But enough about me.",
    "Let's talk about you.",
    "What brings you here?",
    "What are your aspirations?",
    "Your dreams?",
    " ",
    "Take a moment to reflect.",
    "Inhale ...",
    "5",
    "4",
    "3",
    "2",
    "1",
    "Hold ...",
    "5",
    "4",
    "3",
    "2",
    "1",
    "Exhale ...",
    "5",
    "4",
    "3",
    "2",
    "1",
    " ",
    " ",
    "Feeling a bit more centered?",
    "Let's carry this calmness forward.",
    " ",
    "In my work, I strive for",
    "clarity, creativity, and compassion.",
    "I believe in the power of design",
    "to make the world a better place.",
    " ",
    "Through each project,",
    "I aim to bring a touch of joy,",
    "a hint of wisdom,",
    "and a spark of inspiration.",
    " ",
    "I know these are big ideals,",
    "but they guide me in everything I do.",
    " ",
    "Now, let's do one more breathing exercise.",
    "Just to seal in this moment.",
    "Ready?",
    " ",
    "Inhale ...",
    "5",
    "4",
    "3",
    "2",
    "1",
    "Hold ...",
    "5",
    "4",
    "3",
    "2",
    "1",
    "Exhale ...",
    "5",
    "4",
    "3",
    "2",
    "1",
    " ",
    " ",
    "Ah.",
    " ",
    "Thank you for joining me.",
    "For sharing this space and time.",
    "I hope you feel a bit more at ease.",
    " ",
    "If you'd like to see more of my work,",
    "feel free to explore my site.",
    "Or stay a while and listen.",
    "The choice is yours.",
    " ",
    "Remember,",
    "You are capable,",
    "You are creative,",
    "And you are important.",
    " ",
    "Peace, love, and inspiration.",
    " ",
    " ",
    "Until next time,",
    "Take care.",
    " ",
    " ",
    " ",
  ];
  
  export default streamText;