const streamText = [
    " ",
    "...",
    "Hello there! 👋",
    "I hope you're doing well.",
    "I'm here to share something special with you.",
    "Before we dive in ...",
    "Can we take a moment together?",
    "Just you and me.",
    "A simple moment of silence.",
    "Right now.",
    "I know it might feel a bit boring.",
    "But let's give it a try.",
    "For the sake of connection.",
    "Plus, being bored is good for you.",
    " ",
    "Let's simply stay still and quiet.",
    "Only for a short moment.",
    "Ready?",
    "Here we go.",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    "...",
    "How do you feel?",
    "It's amazing how stillness",
    "can change our state of mind.",
    " ",
    "Now, let me tell you a bit about myself.",
    "I'm a creator,",
    "an innovator,",
    "and a dreamer.",
    "I've spent years crafting designs,",
    "building solutions,",
    "and bringing ideas to life.",
    " ",
    "My journey has taken me through",
    "many adventures in the tech world.",
    "From startups to established firms.",
    "Each step teaching me something new.",
    " ",
    "But enough about me.",
    "Let's talk about you.",
    "What brings you here?",
    "What are your aspirations?",
    "Your dreams?",
    " ",
    "Take a moment to reflect.",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    "...",
    "In my work, I strive for",
    "clarity, creativity, and compassion.",
    "I believe in the power of design",
    "to make the world a better place.",
    " ",
    "Through each project,",
    "I aim to bring a touch of joy,",
    "a hint of wisdom,",
    "and a spark of inspiration.",
    " ",
    "I know these are big ideals,",
    "but they guide me in everything I do.",
    " ",
    " ",
    "Thank you for joining me.",
    "For sharing this space and time.",
    " ",
    "If you'd like to see more of my work,",
    "feel free to explore my site.",
    "Or stay a while and listen.",
    "The choice is yours.",
    " ",
    "Remember,",
    "You are capable,",
    "You are creative,",
    "And you are important.",
    " ",
    "Peace, love, and inspiration.",
    " ",
    " ",
    "Until next time,",
    "Take care.",
    " ",
    " ",
    " ",
  ];
  
  export default streamText;